version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
    prepare-dependencies:
        docker:
            - image: node:current-alpine
        steps:
            - checkout
            - run:
                  name: Compute version number
                  command: echo "0.0.${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1:0:7}" | tee version.txt
            - restore_cache:
                  keys:
                      - yarn-deps-{{ checksum "yarn.lock" }}
                      - yarn-deps
            - run:
                  name: yarn install
                  command: yarn install
            - save_cache:
                  paths:
                      - node_modules
                  key: yarn-deps-{{ checksum "yarn.lock" }}-{{ epoch }}
            - store_artifacts:
                  path: yarn.lock
            - persist_to_workspace:
                  root: .
                  paths:
                      - .

    build:
        docker:
            - image: node:current-alpine
        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: build
                  command: |
                      yarn build
            - store_artifacts:
                  path: build/index.js
            - persist_to_workspace:
                  root: .
                  paths:
                      - .

    test:
        docker:
            - image: node:current-alpine
        parallelism: 1
        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: Run tests
                  command: |
                      yarn test
    deploy:
      executor: heroku/default
      steps:
        - checkout
        - heroku/install
        - run:
            command: >
              echo "The command above installs Heroku, the command below deploys.
              What you do inbetween is up to you!"
        - heroku/deploy-via-git

workflows:
    version: 2
    build-test-deploy:
        jobs:
            - prepare-dependencies
            - build:
                  requires:
                      - prepare-dependencies
            - test:
                  requires:
                      - prepare-dependencies
            # Hmm, not the cleanest way, we build in CircleCI but heroku will build again.
            #  Don't do this in production
            - deploy:
                requires:
                  - test
                  - build
