version: 2.1

# Orbs are shareable packages of CircleCI configuration you can use to simplify your builds.
orbs:
  # The Heroku orb is used to simplify the deployment to Heroku
  heroku: circleci/heroku@1.2.6

# A CircleCI pipeline is composed via the following concepts:
# A workflow
#   has multiple jobs
#     and jobs are composed of one or more few steps.

# The workflow configures how the different jobs relate to each other.
# Some jobs might depend on each other. For example, you only want to deploy when the tests succeeded.
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build

jobs:
    # This job builds the application.
    build:
        docker:
            - image: node:current-alpine
        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: build
                  # The yarn build command is configured in the package.json under scripts
                  command: |
                      yarn build
            - store_artifacts:
                  path: build/index.js
            - persist_to_workspace:
                  root: .
                  paths:
                      - .
    # Our pipeline is responsible for testing our software.
    # If one or more tests fail, the deployment shouldn't get executed.
    test:
        docker:
            - image: node:current-alpine
        parallelism: 1
        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: Run tests
                  # The test command is configured in the package.json.
                  command: |
                      yarn test
    deploy:
      executor: heroku/default
      steps:
        - attach_workspace:
              at: .
        # Use the Heroku orb and deploy via heroku's git repository.
        # This step needs the HEROKU_API_KEY and HEROKU_APP_NAME variables to be set.
        # See Readme.md for details.
        - heroku/deploy-via-git
